apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: scd-project-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: scd-project-backend
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30008